# Statistics

In [1]:
import numpy as np

In [12]:
a=np.array([20,34,50,90,12])

In [13]:
a

array([20, 34, 50, 90, 12])

# Mean

In [14]:
np.mean(a)

41.2

# Median

In [15]:
np.median(a)

34.0

In [16]:
b=np.array([234,123,456,675,789,345])

In [17]:
b

array([234, 123, 456, 675, 789, 345])

In [18]:
np.mean(b)

437.0

In [19]:
np.median(b)

400.5

In [22]:
c=np.array([[23,43,50],[21,54,24]])

In [23]:
c

array([[23, 43, 50],
       [21, 54, 24]])

In [27]:
np.mean(c, axis=0)  # axis=0 working with column wise

array([22. , 48.5, 37. ])

In [26]:
np.mean(c, axis=1)  #axis=1 working with row wise

array([38.66666667, 33.        ])

In [28]:
np.median(c, axis=0)

array([22. , 48.5, 37. ])

In [29]:
np.median(c, axis=1)

array([43., 24.])

In [30]:
a

array([20, 34, 50, 90, 12])

In [31]:
np.var(a)

762.5600000000001

In [32]:
round(np.var(a), 2)

762.56

In [33]:
round(np.std(a), 2)

27.61

In [34]:
round(np.var(b),2)

54863.0

In [35]:
round(np.std(c),2)

13.58

In [36]:
c

array([[23, 43, 50],
       [21, 54, 24]])

In [37]:
np.var(c, axis=0)

array([  1.  ,  30.25, 169.  ])

In [38]:
np.var(c, axis=1)

array([130.88888889, 222.        ])

In [39]:
np.std(c, axis=0)

array([ 1. ,  5.5, 13. ])

In [40]:
np.std(c, axis=1)

array([11.4406682 , 14.89966443])

In [41]:
np.min(a)

12

In [42]:
np.max(a)

90

# Range

In [43]:
myrange=np.max(a)-np.min(a)

In [44]:
myrange

78

In [46]:
d=np.array([[23,10,45,20],[13,14,56,76],[90,78,45,77]])

In [47]:
d

array([[23, 10, 45, 20],
       [13, 14, 56, 76],
       [90, 78, 45, 77]])

In [48]:
round(np.var(d),2)

794.58

# Variance

In [51]:
np.var((d),axis=0)

array([1168.66666667,  970.66666667,   26.88888889,  709.55555556])

# Standard Deviation

In [52]:
round(np.std(d), 2)

28.19

In [53]:
np.std(d, axis=1)

array([12.77693234, 27.18800287, 16.68082732])

# Hypothesis Testing

In [28]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [72]:
hyp=pd.read_csv("student_mark.csv")

In [73]:
hyp

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   
5      Annu      F  05-04-1988     45       87         52       89       55   
6     pooja      F  04-05-1987     55       64         61       58       75   
7    Ritesh      M  25-05-1989     54       76         87       56       25   
8     Farha      F  12-08-1990     55       63         89       75       78   
9    Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
5         89       87      52  
6         58       64      61  
7         56       76      87  
8         75       63      89  
9         83       46      77

In [74]:
hyp.head()

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53

In [75]:
n=hyp['Maths'].mean()

In [76]:
round(n,2)

59.6

In [77]:
alpha=0.05
mu=50
xbar=59.6

In [78]:
hyp.isna().sum()

Name         0
Gender       0
DOB          0
Maths        0
Physics      0
Chemistry    0
English      0
Biology      0
Economics    0
History      0
Civics       0
dtype: int64

# 1 Sample Test

In [79]:
s, p=st.ttest_1samp(hyp.Maths, mu)

In [80]:
s

1.55997345901068

In [81]:
p

0.1531976290803191

In [82]:
hyp[hyp['Maths']>50].head()

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   
6     pooja      F  04-05-1987     55       64         61       58       75   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
3         89       75      45  
4         77       83      53  
6         58       64      61

# Paired Sample

In [83]:
t,p=st.ttest_rel(hyp.Maths, hyp.Chemistry)

In [84]:
t

-2.150684931506849

In [85]:
p

0.05996977672153427

In [90]:
hyp

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   
5      Annu      F  05-04-1988     45       87         52       89       55   
6     pooja      F  04-05-1987     55       64         61       58       75   
7    Ritesh      M  25-05-1989     54       76         87       56       25   
8     Farha      F  12-08-1990     55       63         89       75       78   
9    Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53  
5         89       87      52  
6         58       64      61  
7         56       76      87  
8         75       63      89  
9         83       46      77

# Changing the gender to 0 and 1

In [93]:
dummy=pd.get_dummies(hyp['Gender'])

In [94]:
dummy

F  M
0  0  1
1  0  1
2  0  1
3  1  0
4  1  0
5  1  0
6  1  0
7  0  1
8  1  0
9  0  1

In [96]:
df=pd.concat((hyp,dummy), axis=1 )

In [97]:
df

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   
5      Annu      F  05-04-1988     45       87         52       89       55   
6     pooja      F  04-05-1987     55       64         61       58       75   
7    Ritesh      M  25-05-1989     54       76         87       56       25   
8     Farha      F  12-08-1990     55       63         89       75       78   
9    Mukesh      M  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  F  M  
0         52       89      65  0  1  
1         61       58       2  0  1  
2         87       56      74  0  1  
3         89       75      45  1  0  
4         77       83      53  1  0  
5         89       87      52  1  0  
6         58       64      61  1  0  
7         56       76      87  0  1  
8         75       63      89  1  0  
9         83       46      77  0  1

In [99]:
df.drop('Gender', axis=1)

Name         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John  05-04-1988     55       45         56       87       21   
1    Suresh  04-05-1987     75       96         78       64       90   
2    Ramesh  25-05-1989     25       54         89       76       95   
3   Jessica  12-08-1990     78       96         86       63       54   
4  Jennifer  02-09-1989     58       96         78       46       96   
5      Annu  05-04-1988     45       87         52       89       55   
6     pooja  04-05-1987     55       64         61       58       75   
7    Ritesh  25-05-1989     54       76         87       56       25   
8     Farha  12-08-1990     55       63         89       75       78   
9    Mukesh  02-09-1989     96       46         77       83       58   

   Economics  History  Civics  F  M  
0         52       89      65  0  1  
1         61       58       2  0  1  
2         87       56      74  0  1  
3         89       75      45  1  0  
4         77       83      53  1  0  
5         89       87      52  1  0  
6         58       64      61  1  0  
7         56       76      87  0  1  
8         75       63      89  1  0  
9         83       46      77  0  1